// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateJobInput struct {
	Title       string  `json:"title"`
	Description *string `json:"description,omitempty"`
}

type Mutation struct {
}

type Query struct {
}
