// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateJobInput struct {
	Title       string  `json:"title"`
	Description *string `json:"description,omitempty"`
}

type DeleteJobInput struct {
	ID string `json:"id"`
}

type Mutation struct {
}

type Query struct {
}

type UpdateJobInput struct {
	Title       *string `json:"title,omitempty"`
	Description *string `json:"description,omitempty"`
	ID          string  `json:"id"`
}
