//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var Company = newCompanyTable("", "company", "")

type companyTable struct {
	sqlite.Table

	// Columns
	ID          sqlite.ColumnString
	Name        sqlite.ColumnString
	Description sqlite.ColumnString

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
}

type CompanyTable struct {
	companyTable

	EXCLUDED companyTable
}

// AS creates new CompanyTable with assigned alias
func (a CompanyTable) AS(alias string) *CompanyTable {
	return newCompanyTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new CompanyTable with assigned schema name
func (a CompanyTable) FromSchema(schemaName string) *CompanyTable {
	return newCompanyTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new CompanyTable with assigned table prefix
func (a CompanyTable) WithPrefix(prefix string) *CompanyTable {
	return newCompanyTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new CompanyTable with assigned table suffix
func (a CompanyTable) WithSuffix(suffix string) *CompanyTable {
	return newCompanyTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newCompanyTable(schemaName, tableName, alias string) *CompanyTable {
	return &CompanyTable{
		companyTable: newCompanyTableImpl(schemaName, tableName, alias),
		EXCLUDED:     newCompanyTableImpl("", "excluded", ""),
	}
}

func newCompanyTableImpl(schemaName, tableName, alias string) companyTable {
	var (
		IDColumn          = sqlite.StringColumn("id")
		NameColumn        = sqlite.StringColumn("name")
		DescriptionColumn = sqlite.StringColumn("description")
		allColumns        = sqlite.ColumnList{IDColumn, NameColumn, DescriptionColumn}
		mutableColumns    = sqlite.ColumnList{NameColumn, DescriptionColumn}
	)

	return companyTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:          IDColumn,
		Name:        NameColumn,
		Description: DescriptionColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
